export enum Permission {
  DASHBOARD_LOGIN = 'DASHBOARD_ACCESS',
  PASSWORD_RESET = 'PASSWORD_RESET',

  ROLE_FIND = 'ROLE_FIND',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  USER_FIND = 'USER_FIND',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  PREDEFINED_DATA_FIND = 'PREDEFINED_DATA_FIND',
  PREDEFINED_DATA_CREATE = 'PREDEFINED_DATA_CREATE',
  PREDEFINED_DATA_UPDATE = 'PREDEFINED_DATA_UPDATE',
  PREDEFINED_DATA_DELETE = 'PREDEFINED_DATA_DELETE',


}
